networks:
  storages:
    driver: bridge
  storages_prod:
    driver: bridge 

services:
  main-app:
    build:
      context: ..
      dockerfile: dev.Dockerfile
    container_name: main-app
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    volumes:
       - ../app/application/:/app/application/
       - ../app/domain/:/app/domain/
       - ../app/infra/:/app/infra/
       - ../app/logic/:/app/logic/
       - ../app/settings/:/app/settings/
       - ../app/tests/:/app/tests/
       - ../app/alembic/:/app/alembic/
       - ../app/alembic.ini:/app/alembic.ini
    networks:
      - storages
    profiles:
      - dev

  main-app-prod:
    build:
      context: ..
      dockerfile: prod.Dockerfile
    container_name: main-app-prod
    restart: unless-stopped
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env.prod
    networks:
      - storages_prod
    profiles:
      - prod
