services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgresql-db-prod
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - ../.env.prod
    networks:
      - storages_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data_prod:
    driver: local

networks:
  storages_prod:
    driver: bridge 