"""add names_origins and countries tables

Revision ID: 20250527_13_15_53
Revises:
Create Date: 2025-05-27 13:15:53.453755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20250527_13_15_53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'countries',
        sa.Column('iso_alpha2_code', sa.String(length=2), nullable=False),
        sa.Column('common_name', sa.String(length=100), nullable=False),
        sa.Column('official_name', sa.String(length=100), nullable=False),
        sa.Column('region', sa.String(length=50), nullable=False),
        sa.Column('sub_region', sa.String(length=50), nullable=True),
        sa.Column('independent', sa.Boolean(), nullable=True),
        sa.Column('capital', sa.String(length=100), nullable=True),
        sa.Column('capital_lat', sa.Float(), nullable=True),
        sa.Column('capital_long', sa.Float(), nullable=True),
        sa.Column('flag_png', sa.String(length=200), nullable=False),
        sa.Column('flag_svg', sa.String(length=200), nullable=False),
        sa.Column('flag_alt', sa.String(length=1000), nullable=True),
        sa.Column('coat_of_arms_png', sa.String(length=200), nullable=True),
        sa.Column('coat_of_arms_svg', sa.String(length=200), nullable=True),
        sa.Column('borders', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('iso_alpha2_code'),
    )
    op.create_table(
        'names_origin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('probability', sa.Float(), nullable=False),
        sa.Column('count_of_requests', sa.Integer(), nullable=False),
        sa.Column('country_code', sa.String(length=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['country_code'],
            ['countries.iso_alpha2_code'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_names_origin_name'), 'names_origin', ['name'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_names_origin_name'), table_name='names_origin')
    op.drop_table('names_origin')
    op.drop_table('countries')
    # ### end Alembic commands ###
