name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"
          enable-cache: true
          cache-dependency-glob: |
            .pre-commit-config.yaml

      - name: Install pre-commit and isort
        run: uv pip install pre-commit isort
        env:
          UV_SYSTEM_PYTHON: 1


      - name: Execute Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always

  test:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Install test dependencies
        run: uv sync --group test

      - name: Install app dependencies
        run: uv sync test

      - name: Test with pytest
        run: uv run pytest
