name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"
          enable-cache: true
          cache-dependency-glob: |
            .pre-commit-config.yaml

      - name: Install pre-commit and isort
        run: uv pip install pre-commit isort
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Execute Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always

  test:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy environment files
        run: |
          cp .env.example .env
          cat .env  # Verify the .env file content

      - name: Build and start containers
        run: make all

      - name: Wait for PostgreSQL to be ready
        run: |
          timeout 30s bash -c 'until docker exec postgresql-db pg_isready -U postgres; do sleep 1; done'

      - name: Run migrations
        run: make migrations

      - name: Run tests
        run: make test

      - name: Stop containers
        if: always()
        run: make all-down
